language: csharp
mono: none
dotnet: 3.1.411
solution: SmlTestTask.sln
before_script:
  - dotnet restore
script:
  - dotnet build SmlTestTask.sln -c Release
  - dotnet test BLL.Test/BLL.Test.csproj
  - dotnet test -c Release --no-build BLL.Test/BLL.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover